///////////////////////////////////////////////////////////////////////////////
// Untitled1Interfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "Untitled1Services.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
